from django.urls import path

from chigame.api.views import UserGroupsView
from chigame.users.views import (
    accept_friend_invitation,
    act_on_inbox_notification,
    bookmark_notification,
    bulk_inbox,
    cancel_friend_invitation,
    decline_friend_invitation,
    friend_list_view,
    name_update_view,
    notification_detail,
    notification_search_results,
    privacy_settings_view,
    remove_friend,
    send_friend_invitation,
    upload_profile_photo,
    user_detail_view,
    user_inbox_view,
    user_list,
    user_profile_detail_view,
    user_redirect_view,
    user_search_results,
    username_update_view,
    view_bookmarked_notifications,
)

from . import views

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update-name/", view=name_update_view, name="update-name"),
    path("~update-username/", view=username_update_view, name="update-username"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
    path("profile/<int:pk>/", view=user_profile_detail_view, name="user-profile"),
    path("privacy-settings/", view=privacy_settings_view, name="privacy-settings"),
    path("add_friend/<int:pk>", view=send_friend_invitation, name="add-friend"),
    path("remove_friend/<int:pk>", view=remove_friend, name="remove-friend"),
    path("cancel_friend_invitation/<int:pk>", view=cancel_friend_invitation, name="cancel-friend-invitation"),
    path("user-detail/", views.user_detail_view, name="user-detail"),
    path("user-list/", view=user_list, name="user-list"),
    path("accept_friend_invitation/<int:pk>", view=accept_friend_invitation, name="accept-friend-invitation"),
    path("decline_friend_invitation/<int:pk>", view=decline_friend_invitation, name="decline-friend-invitation"),
    path("user_history/<int:pk>", views.user_history, name="user-history"),
    path("search-results", view=user_search_results, name="user-search-results"),
    path("notifications/search-results", view=notification_search_results, name="notification-search-results"),
    path("inbox/<int:pk>/", view=user_inbox_view, name="user-inbox"),
    path("profile/<int:pk>/friends", view=friend_list_view, name="friend-list"),
    path("inbox/<int:pk>/deleted_notifications", views.deleted_notifications_view, name="deleted-notifications"),
    path("notification_detail/<int:pk>", view=notification_detail, name="notification-detail"),
    path(
        "act_on_inbox_notification/<int:pk>/<str:action>",
        view=act_on_inbox_notification,
        name="act-on-inbox-notification",
    ),
    path("bulk-action/", view=bulk_inbox, name="bulk-inbox"),
    path("<slug:slug>/groups/", UserGroupsView.as_view(), name="api-user-groups"),
    path("notifications/<int:pk>/bookmark/", view=bookmark_notification, name="bookmark-notification"),
    path("notifications/<int:pk>/bookmarked/", view=view_bookmarked_notifications, name="bookmarked-notifications"),
    path("upload-photo/", upload_profile_photo, name="upload-photo"),
    path("notifications/<int:pk>/move/", views.move_notification, name="move-notification"),
    path("labels/create/", views.create_notification_label, name="create-notification-label"),
    path("labels/<int:label_id>/notifications/", views.notifications_by_label, name="notifications-by-label"),
    path("inbox/<int:pk>/<str:category>/", views.user_inbox_view, name="user-inbox-category"),
]
