# Generated by Django 4.2.20 on 2025-05-21 18:00

import chigame.chat.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LiveChat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("public", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="LiveChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
                ("edited", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="LiveChatMessageReaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.CharField(max_length=10, validators=[chigame.chat.validators.validate_emoji])),
            ],
        ),
        migrations.CreateModel(
            name="LiveChatPoll",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(help_text="The date and time the poll will be closed", null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LiveChatPollOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="LiveChatPollVote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="LiveChatUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("live_chat", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chat.livechat")),
            ],
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name="LiveChatPollVote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "option",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chat.livechatpolloption"),
                ),
                ("poll", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chat.livechatpoll")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="livechatpoll",
            name="options",
            field=models.ManyToManyField(blank=True, related_name="polls", to="chat.livechatpolloption"),
        ),
        migrations.CreateModel(
            name="LiveChatMessageReaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.CharField(max_length=10, validators=[chigame.chat.validators.validate_emoji])),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chat.livechatmessage")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="livechat",
            name="users",
            field=models.ManyToManyField(
                related_name="live_chats", through="chat.LiveChatUser", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="livechatpollvote",
            constraint=models.UniqueConstraint(fields=("poll", "option", "user"), name="unique_poll_option_user"),
        ),
        migrations.AlterUniqueTogether(
            name="livechatmessagereaction",
            unique_together={("user", "message", "content")},
        ),
>>>>>>> parent of 7186be2c (Merge branch 'dev' into word-game-versus-css)
    ]
