# Generated by Django 4.2.20 on 2025-05-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livechatuser",
            name="profanity",
            field=models.BooleanField(default=True),
        ),
    ]
