# Generated by Django 5.2.1 on 2025-05-19 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="livechatmessage",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="livechatmessagereaction",
            name="message",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chat.livechatmessage"),
        ),
        migrations.AddField(
            model_name="livechatmessagereaction",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="livechatuser",
            name="live_chat",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chat.livechat"),
        ),
        migrations.AddField(
            model_name="livechatuser",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="livechat",
            name="users",
            field=models.ManyToManyField(
                related_name="live_chats", through="chat.LiveChatUser", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="livechatmessagereaction",
            unique_together={("user", "message", "content")},
        ),
    ]
