# Generated by Django 4.2.20 on 2025-05-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="livechat",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
