# Generated by Django 4.2.20 on 2025-05-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="livechatmessage",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
