# Generated by Django 4.2.20 on 2025-05-13 05:14

from django.conf import settings
from django.db import migrations, models, connection
import django.db.models.deletion


def check_table_exists(apps, schema_editor):
    """
    Check if the table already exists, and if it does, make sure the model is 
    registered in the Django model registry.
    """
    cursor = connection.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='chat_livechatmessagereaction';")
    table_exists = bool(cursor.fetchone())
    
    # Table was already created in the 0001_initial migration
    # This is just to prevent errors


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        # The LiveChatMessageReaction model is already created in the initial migration
        # This RunPython operation is just to verify the table exists
        migrations.RunPython(
            check_table_exists,
            migrations.RunPython.noop
        ),
    ]
