# Generated by Django 4.2.20 on 2025-05-23 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="livechatuser",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="livechatpollvote",
            name="option",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chat.livechatpolloption"),
        ),
        migrations.AddField(
            model_name="livechatpollvote",
            name="poll",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chat.livechatpoll"),
        ),
        migrations.AddField(
            model_name="livechatpollvote",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="livechatpoll",
            name="live_chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="polls", to="chat.livechat"
            ),
        ),
        migrations.AddField(
            model_name="livechatpoll",
            name="options",
            field=models.ManyToManyField(blank=True, related_name="polls", to="chat.livechatpolloption"),
        ),
        migrations.AddField(
            model_name="livechatmessagereaction",
            name="message",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chat.livechatmessage"),
        ),
        migrations.AddField(
            model_name="livechatmessagereaction",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="livechatmessage",
            name="live_chat",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chat.livechat"),
        ),
        migrations.AddField(
            model_name="livechatmessage",
            name="reply_to",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="chat.livechatmessage"
            ),
        ),
        migrations.AddField(
            model_name="livechatmessage",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="livechat",
            name="users",
            field=models.ManyToManyField(
                related_name="live_chats", through="chat.LiveChatUser", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="livechatpollvote",
            constraint=models.UniqueConstraint(fields=("poll", "option", "user"), name="unique_poll_option_user"),
        ),
        migrations.AlterUniqueTogether(
            name="livechatmessagereaction",
            unique_together={("user", "message", "content")},
        ),
    ]
