# Generated by Django 4.2.20 on 2025-05-13 05:14

from django.conf import settings
from django.db import migrations, models, connection
import django.db.models.deletion


def create_message_reaction_table(apps, schema_editor):
    """
    Create the LiveChatMessageReaction table only if it doesn't exist already.
    This avoids issues with duplicate tables during migrations.
    """
    cursor = connection.cursor()
    
    # Check if the table already exists
    cursor.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name='chat_livechatmessagereaction';"
    )
    if cursor.fetchone():
        # Table already exists, do nothing
        return
    
    # If we're here, the table doesn't exist yet
    # Schema editor will create the table via the CreateModel operation


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_message_reaction_table,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="LiveChatMessageReaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.CharField(max_length=10)),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chat.livechatmessage")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "message", "content")},
            },
        ),
    ]
