# Generated by Django 4.2.20 on 2025-05-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_livechatuser_profanity"),
    ]

    operations = [
        migrations.AddField(
            model_name="livechat",
            name="profanity_allowed",
            field=models.BooleanField(default=False),
        ),
    ]
