# Generated by Django 4.2.20 on 2025-05-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_livechat_description_livechatuser_profanity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livechatuser",
            name="profanity",
            field=models.BooleanField(default=False),
        ),
    ]
