# Generated by Django 4.2.20 on 2025-05-22 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_livechat_pinned_message"),
        ("chat", "0002_livechatmessage_edited"),
    ]

    operations = []
