# Generated by Django 4.2.20 on 2025-05-20 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_livechatmessagereaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveChatPoll",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(help_text="The date and time the poll will be closed", null=True)),
                ("live_chat", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chat.livechat")),
            ],
        ),
        migrations.CreateModel(
            name="LiveChatPollOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="livechatmessagereaction",
            name="content",
            field=models.CharField(help_text="Up to 10 emoji characters", max_length=10),
        ),
        migrations.CreateModel(
            name="LiveChatPollVote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "option",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chat.livechatpolloption"),
                ),
                ("poll", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chat.livechatpoll")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="livechatpoll",
            name="options",
            field=models.ManyToManyField(blank=True, related_name="polls", to="chat.livechatpolloption"),
        ),
        migrations.AddConstraint(
            model_name="livechatpollvote",
            constraint=models.UniqueConstraint(fields=("poll", "option", "user"), name="unique_poll_option_user"),
        ),
    ]
