# Generated by Django 4.2.20 on 2025-05-20 05:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_livechatmessage_reply_to_livechatmessagereaction"),
        ("chat", "0002_livechatmessagereaction"),
    ]

    operations = []
