# Generated by Django 4.2.20 on 2025-05-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_livechat_pinned_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livechat",
            name="pinned_message",
        ),
        migrations.AddField(
            model_name="livechatmessage",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
