# Generated by Django 4.2.20 on 2025-05-13 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_livechatmessage_reply_to_livechatmessagereaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livechatmessage",
            name="reply_to",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="chat.livechatmessage"
            ),
        ),
    ]
