# Generated by Django 4.2.20 on 2025-05-15 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_alter_livechatmessage_reply_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="livechat",
            name="pinned_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pinned_message",
                to="chat.livechatmessage",
            ),
        ),
    ]
