# Generated by Django 4.2.20 on 2025-05-23 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_livechatmessage_reply_to_livechatmessagereaction"),
        ("chat", "0003_merge_20250522_1426"),
    ]

    operations = []
