# Generated by Django 4.2.20 on 2025-05-21 05:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_livechatmessagereaction"),
        ("chat", "0003_alter_livechatmessage_reply_to"),
    ]

    operations = []
