# Generated by Django 4.2.20 on 2025-05-26 20:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_livechatuser_profanity"),
        ("chat", "0003_alter_livechatuser_profanity"),
    ]

    operations = []
