# Generated by Django 4.2.20 on 2025-05-20 05:15

from django.db import migrations, connection
from django.db.migrations.state import ModelState
from django.db.models import Model


def handle_duplicate_model(apps, schema_editor):
    """
    This function handles the duplication of LiveChatMessageReaction model
    by ensuring that the database table exists correctly and has the right structure.
    
    We need this because the model was defined both in 0001_initial.py and 0002_livechatmessagereaction.py
    """
    # This script checks the state of the table and ensures any model constraints
    # are properly enforced
    
    # Get the name of the database backend
    db_name = schema_editor.connection.vendor
    
    # For sqlite
    if db_name == 'sqlite':
        cursor = connection.cursor()
        
        # 1. Make sure columns have the right type and constraints
        cursor.execute("""
            PRAGMA table_info('chat_livechatmessagereaction');
        """)
        columns = {col[1]: col for col in cursor.fetchall()}
        
        # 2. Ensure uniqueness constraint exists
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='index' AND tbl_name='chat_livechatmessagereaction'
            AND sql LIKE '%UNIQUE%user_id%message_id%content%';
        """)
        unique_constraint_exists = bool(cursor.fetchone())
        
        if not unique_constraint_exists:
            # Add the uniqueness constraint if it doesn't exist
            cursor.execute("""
                CREATE UNIQUE INDEX IF NOT EXISTS chat_livechatmessagereaction_user_message_content_unique
                ON chat_livechatmessagereaction (user_id, message_id, content);
            """)


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_livechatpoll_livechatpolloption_and_more"),
    ]

    operations = [
        migrations.RunPython(
            handle_duplicate_model,
            migrations.RunPython.noop
        ),
    ]
