# Generated by Django 4.2.20 on 2025-05-20 05:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_merge_20250520_0001"),
    ]

    operations = []
