# Generated by Django 4.2.20 on 2025-05-23 04:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_merge_20250522_1426"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livechat",
            name="pinned_message",
        ),
    ]
