# Generated by Django 5.1.7 on 2025-05-26 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_merge_20250522_1426"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livechat",
            name="pinned_message",
        ),
    ]
