# Generated by Django 4.2.20 on 2025-05-20 02:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_livechatmessagereaction"),
        ("chat", "0003_livechatmessagereaction"),
    ]

    operations = []
