# Generated by Django 4.2.20 on 2025-05-20 05:05

from django.db import migrations, connection


def check_and_fix_table(apps, schema_editor):
    """
    Handle the case where LiveChatMessageReaction table may have been created multiple times.
    This function ensures the table exists with the correct structure.
    """
    # SQLite-specific check
    cursor = connection.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='chat_livechatmessagereaction';")
    table_exists = cursor.fetchone() is not None

    if not table_exists:
        return  # Table doesn't exist, nothing to fix

    # Check if the table has the correct structure
    try:
        # If we can query the table, it exists and has the correct structure
        cursor.execute("SELECT id, content, message_id, user_id FROM chat_livechatmessagereaction LIMIT 1;")
    except Exception:
        # Table exists but might be corrupted, drop and let Django recreate
        cursor.execute("DROP TABLE IF EXISTS chat_livechatmessagereaction;")


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_merge_20250520_0001"),
    ]

    operations = [
        migrations.RunPython(
            check_and_fix_table,
            migrations.RunPython.noop,
        ),
    ]
