# Generated by Django 4.2.20 on 2025-05-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_alter_livechatmessage_reply_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="livechatmessage",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
