# Generated by Django 4.2.20 on 2025-05-25 06:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_livechat_description"),
        ("chat", "0003_merge_20250522_1426"),
    ]

    operations = []
