# Generated by Django 4.2.20 on 2025-05-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_livechatmessage_reply_to_edited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livechatmessagereaction",
            name="content",
            field=models.CharField(help_text="Up to 10 emoji characters", max_length=10),
        ),
    ]
