# Generated by Django 4.2.20 on 2025-05-20 02:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_livechatmessage_edited"),
        ("chat", "0004_merge_20250519_2131"),
    ]

    operations = []
