# Generated by Django 4.2.20 on 2025-05-21 05:05

import chigame.chat.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_merge_20250521_0004"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livechatmessagereaction",
            name="content",
            field=models.CharField(max_length=10, validators=[chigame.chat.validators.validate_emoji]),
        ),
    ]
