# Generated by Django 4.2.20 on 2025-05-21 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_alter_livechatmessagereaction_content"),
        ("chat", "0004_fix_livechatmessagereaction_duplication"),
        ("chat", "0005_alter_livechatmessagereaction_content"),
    ]

    operations = []
