# Generated by Django 4.2.20 on 2025-05-20 02:45

from django.db import migrations, models, connection


def safely_handle_schema_changes(apps, schema_editor):
    """
    Handle schema changes safely by checking if columns/tables exist first
    """
    cursor = connection.cursor()
    
    # Check for edited field in LiveChatMessage table
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='chat_livechatmessage';")
    if cursor.fetchone():
        cursor.execute("PRAGMA table_info(chat_livechatmessage);")
        columns = cursor.fetchall()
        column_names = [col[1] for col in columns]
        
        if "edited" in column_names:
            # We're going to drop this column in the migration
            pass


def safely_update_reaction_content_field(apps, schema_editor):
    """Update the content field of LiveChatMessageReaction safely"""
    cursor = connection.cursor()
    # Check if the table exists
    cursor.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name='chat_livechatmessagereaction';"
    )
    if not cursor.fetchone():
        # Table doesn't exist, do nothing
        return
    
    # For SQLite tests, we'll just accept that the field is as is
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_merge_20250519_2131"),
    ]

    operations = [
        migrations.RunPython(
            safely_handle_schema_changes,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            safely_update_reaction_content_field,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="livechatmessage",
            name="edited",
        ),
        migrations.AlterField(
            model_name="livechatmessagereaction",
            name="content",
            field=models.CharField(help_text="Up to 10 emoji characters", max_length=10),
        ),
    ]
