# Generated by Django 4.2.20 on 2025-05-21 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_alter_livechatmessagereaction_content"),
        ("chat", "0006_remove_livechatmessage_edited_and_more"),
    ]

    operations = []
