# Generated by Django 4.2.20 on 2025-05-23 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("spoiler", models.BooleanField(default=False)),
                (
                    "rarity",
                    models.IntegerField(choices=[(1, "Common"), (2, "Uncommon"), (3, "Rare"), (4, "Precious")]),
                ),
                ("threshold", models.FloatField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pinned", models.BooleanField(default=False)),
                ("date_earned", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("progress", models.FloatField(blank=True, default=1, null=True)),
                (
                    "achievement",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="achievements.achievement"),
                ),
            ],
        ),
    ]
