# Generated by Django 5.2.1 on 2025-05-20 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("achievements", "0001_initial"),
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="game",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.game"),
        ),
        migrations.AddField(
            model_name="userachievement",
            name="achievement",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="achievements.achievement"),
        ),
    ]
