# Generated by Django 4.2.20 on 2025-05-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0028_remove_livechatmessage_live_chat_id_and_more"),
        ("achievements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="threshold",
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name="userachievement",
            name="progress",
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="spoiler",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userachievement",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="achievement",
            unique_together={("name", "game")},
        ),
    ]
