# Generated by Django 4.2.20 on 2025-05-23 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("achievements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userachievement",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="achievement",
            name="game",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.game"),
        ),
        migrations.AlterUniqueTogether(
            name="userachievement",
            unique_together={("user", "achievement")},
        ),
        migrations.AlterUniqueTogether(
            name="achievement",
            unique_together={("name", "game")},
        ),
    ]
