# Generated by Django 4.2.20 on 2025-05-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0002_achievement_threshold_userachievement_progress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userachievement",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userachievement",
            name="date_earned",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
