# Generated by Django 4.2.20 on 2025-05-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0003_userachievement_last_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userachievement",
            name="last_updated",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
