# Generated by Django 4.2.20 on 2025-05-26 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0003_userachievement_last_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userachievement",
            name="last_updated",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2025, 5, 26, 20, 56, 19, 658244, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
