# Generated by Django 4.2.20 on 2025-05-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0004_alter_userachievement_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userachievement",
            name="last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
