# Generated by Django 4.2.4 on 2023-11-08 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("max_players", models.PositiveIntegerField()),
                ("description", models.TextField()),
                ("rules", models.TextField()),
                ("draw_rules", models.TextField()),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.game")),
                ("matches", models.ManyToManyField(related_name="matches", to="games.match")),
                ("players", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                (
                    "winners",
                    models.ManyToManyField(blank=True, related_name="won_tournaments", to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
