# Generated by Django 4.2.4 on 2023-11-06 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_games_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lobby",
            name="game_mod_status",
            field=models.PositiveSmallIntegerField(choices=[(1, "Default Game"), (2, "Modified Game")], default=1),
        ),
        migrations.AddField(
            model_name="lobby",
            name="lobby_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="lobby",
            name="match_status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Lobbied"), (2, "In-Progress"), (3, "Finished")], default=1
            ),
        ),
        migrations.AddField(
            model_name="lobby",
            name="time_constraint",
            field=models.PositiveIntegerField(default=3),
        ),
    ]
