# Generated by Django 4.2.4 on 2023-11-07 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_games_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="winners",
        ),
        migrations.AddField(
            model_name="match",
            name="date_played",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="outcome",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "win"), (1, "draw"), (2, "lose"), (3, "withdrawal")], default=1
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="role",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="team",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="victory_type",
            field=models.TextField(blank=True, null=True),
        ),
    ]
