# Generated by Django 4.2.4 on 2023-12-02 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tournaments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="game",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.game"),
        ),
        migrations.AddField(
            model_name="tournament",
            name="matches",
            field=models.ManyToManyField(blank=True, related_name="matches", to="games.match"),
        ),
        migrations.AddField(
            model_name="tournament",
            name="players",
            field=models.ManyToManyField(blank=True, related_name="joined_tournaments", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="tournament",
            name="winners",
            field=models.ManyToManyField(blank=True, related_name="won_tournaments", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="publisher",
            name="games",
            field=models.ManyToManyField(related_name="publishers", to="games.game"),
        ),
        migrations.AddField(
            model_name="player",
            name="match",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.match"),
        ),
        migrations.AddField(
            model_name="player",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="person",
            name="games",
            field=models.ManyToManyField(related_name="people", to="games.game"),
        ),
        migrations.AddField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.chat"),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="matchproposal",
            name="game",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.game"),
        ),
        migrations.AddField(
            model_name="matchproposal",
            name="group",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.group"),
        ),
        migrations.AddField(
            model_name="matchproposal",
            name="joined",
            field=models.ManyToManyField(blank=True, related_name="joined_matches", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="matchproposal",
            name="proposer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="match",
            name="game",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.game"),
        ),
        migrations.AddField(
            model_name="match",
            name="lobby",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="games.lobby"),
        ),
        migrations.AddField(
            model_name="match",
            name="players",
            field=models.ManyToManyField(through="games.Player", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="lobby",
            name="created_by",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="lobby",
            name="game",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.game"),
        ),
        migrations.AddField(
            model_name="lobby",
            name="members",
            field=models.ManyToManyField(related_name="lobbies", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="game",
            name="categories",
            field=models.ManyToManyField(blank=True, related_name="games", to="games.category"),
        ),
        migrations.AddField(
            model_name="game",
            name="mechanics",
            field=models.ManyToManyField(blank=True, related_name="games", to="games.mechanic"),
        ),
        migrations.AddField(
            model_name="chat",
            name="tournament",
            field=models.OneToOneField(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="games.tournament"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="recipients",
            field=models.ManyToManyField(related_name="announcements", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="announcement",
            name="sender",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
