# Generated by Django 4.2.4 on 2023-11-07 21:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_initial_matches"),
        ("games", "0002_lobby"),
    ]

    operations = []
