# Generated by Django 4.2.4 on 2023-11-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_game_bgg_id_game_complexity_game_expected_playtime_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mechanic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("person_role", models.PositiveSmallIntegerField(choices=[(1, "Designer"), (2, "Artist")])),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True)),
                ("year_established", models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="suggested_age",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="BGG_id",
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="image",
            field=models.URLField(default="/static/images/no_picture_available.png"),
        ),
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="People",
        ),
        migrations.AddField(
            model_name="publisher",
            name="games",
            field=models.ManyToManyField(related_name="publishers", to="games.game"),
        ),
        migrations.AddField(
            model_name="person",
            name="games",
            field=models.ManyToManyField(related_name="people", to="games.game"),
        ),
        migrations.AddField(
            model_name="game",
            name="category",
            field=models.ManyToManyField(related_name="games", to="games.category"),
        ),
        migrations.AddField(
            model_name="game",
            name="mechanics",
            field=models.ManyToManyField(related_name="games", to="games.mechanic"),
        ),
    ]
