# Generated by Django 4.2.4 on 2023-11-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mechanic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="BGG_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="complexity",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="expected_playtime",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="image",
            field=models.URLField(default="/static/images/no_picture_available.png"),
        ),
        migrations.AddField(
            model_name="game",
            name="max_playtime",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="min_playtime",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="rules",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="suggested_age",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="year_published",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("website", models.URLField(null=True)),
                ("year_established", models.PositiveIntegerField(null=True)),
                ("games", models.ManyToManyField(related_name="publishers", to="games.game")),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("person_role", models.PositiveSmallIntegerField(choices=[(1, "Designer"), (2, "Artist")])),
                ("games", models.ManyToManyField(related_name="people", to="games.game")),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="category",
            field=models.ManyToManyField(related_name="games", to="games.category"),
        ),
        migrations.AddField(
            model_name="game",
            name="mechanics",
            field=models.ManyToManyField(related_name="games", to="games.mechanic"),
        ),
    ]
