# Generated by Django 4.2.4 on 2023-11-06 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="match",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="games.match"),
        ),
    ]
