# Generated by Django 4.2.4 on 2023-11-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_category_mechanic_person_publisher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publisher",
            name="website",
            field=models.URLField(null=True),
        ),
    ]
