# Generated by Django 4.2.4 on 2023-11-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_merge_0002_initial_matches_0002_lobby"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lobby",
            name="time_constraint",
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name="player",
            name="outcome",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(0, "win"), (1, "draw"), (2, "lose"), (3, "withdrawal")], null=True
            ),
        ),
    ]
