<<<<<<< HEAD
# Generated by Django 4.2.4 on 2023-11-07 06:27

from django.conf import settings
=======
# Generated by Django 4.2.4 on 2023-11-06 03:56

>>>>>>> 26a1080b267fcb2e7094951f51b343cad7f2af31
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="receipients",
            new_name="recipients",
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
=======
        ("games", "0003_category_mechanic_game_bgg_id_game_complexity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="match",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="games.match"),
>>>>>>> 26a1080b267fcb2e7094951f51b343cad7f2af31
        ),
    ]
