# Generated by Django 4.2.4 on 2023-11-10 04:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_category_mechanic_game_bgg_id_game_complexity_and_more"),
        ("games", "0004_initial"),
    ]

    operations = []
