# Generated by Django 4.2.4 on 2023-11-07 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_lobby"),
        ("games", "0004_alter_publisher_website"),
    ]

    operations = []
