# Generated by Django 4.2.4 on 2023-11-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="matches",
            field=models.ManyToManyField(blank=True, related_name="matches", to="games.match"),
        ),
    ]
