# Generated by Django 4.2.4 on 2023-11-12 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0004_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="winners",
        ),
        migrations.AddField(
            model_name="match",
            name="date_played",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="outcome",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(0, "win"), (1, "draw"), (2, "lose"), (3, "withdrawal")], null=True
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="role",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="team",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="victory_type",
            field=models.TextField(blank=True, null=True),
        ),
    ]
