# Generated by Django 4.2.4 on 2023-11-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="BGG_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="category",
            field=models.ManyToManyField(blank=True, related_name="games", to="games.category"),
        ),
        migrations.AlterField(
            model_name="game",
            name="complexity",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="expected_playtime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="max_playtime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="mechanics",
            field=models.ManyToManyField(blank=True, related_name="games", to="games.mechanic"),
        ),
        migrations.AlterField(
            model_name="game",
            name="min_playtime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="suggested_age",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="year_published",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
