# Generated by Django 4.2.4 on 2023-11-13 22:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0006_matches_nullable_outcome"),
        ("games", "0007_image_field_as_text"),
    ]

    operations = []
