# Generated by Django 4.2.4 on 2023-11-14 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0008_merge_20231113_1632"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("sent", models.BooleanField(default=False)),
                (
                    "type",
                    models.PositiveIntegerField(
                        choices=[(2, "REMINDER"), (3, "UPCOMING_MATCH"), (4, "MATCH_PROPOSAL")]
                    ),
                ),
                ("recipients", models.ManyToManyField(related_name="announcements", to=settings.AUTH_USER_MODEL)),
                (
                    "sender",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
