# Generated by Django 4.2.4 on 2023-11-15 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0009_announcement_delete_notification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="category",
            new_name="categories",
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.TextField(default="/static/images/no_picture_available.png"),
        ),
        migrations.AddField(
            model_name="mechanic",
            name="image",
            field=models.TextField(default="/static/images/no_picture_available.png"),
        ),
        migrations.AlterField(
            model_name="game",
            name="complexity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=3,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
            ),
        ),
    ]
