# Generated by Django 4.2.4 on 2023-11-14 23:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0009_announcement_delete_notification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="category",
            new_name="categories",
        ),
    ]
