# Generated by Django 4.2.20 on 2025-05-19 20:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_base", "0001_initial"),
        ("games", "0010_checkers_checkersboard_checkersturn_feedback_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="published_guide_id",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="knowledge_base.guide"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="twine_file",
            field=models.FileField(blank=True, null=True, upload_to="twine_games/"),
        ),
        migrations.AddField(
            model_name="game",
            name="users",
            field=models.ManyToManyField(blank=True, related_name="games", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="mechanic",
            name="image",
            field=models.TextField(default="/static/images/no_picture_available.png"),
        ),
        migrations.AddField(
            model_name="message",
            name="token_id",
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name="message",
            name="update_on",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tournament",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tournaments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="num_winner",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="tournament",
            name="registration_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="registration_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="tournament_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="tournament_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="complexity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=3,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="year_published",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="matches",
            field=models.ManyToManyField(blank=True, related_name="tournament", to="games.match"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="players",
            field=models.ManyToManyField(blank=True, related_name="joined_tournaments", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="review",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="games.game"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="gamelist",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="game_lists", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="gamelist",
            name="games",
            field=models.ManyToManyField(blank=True, related_name="game_lists", to="games.game"),
        ),
        migrations.AddField(
            model_name="feedback",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="feedback", to="games.tournament"
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="checkersturn",
            name="board",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.checkersboard"),
        ),
        migrations.AddField(
            model_name="checkersturn",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="turns", to="games.checkers"
            ),
        ),
        migrations.AddField(
            model_name="checkersturn",
            name="player",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.player"),
        ),
        migrations.AddField(
            model_name="checkers",
            name="player_1",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.player"),
        ),
        migrations.AddField(
            model_name="checkers",
            name="player_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkers_player_2",
                to="games.player",
            ),
        ),
        migrations.AddField(
            model_name="checkers",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkers_winner",
                to="games.player",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="checkersturn",
            unique_together={("game", "turn_number")},
        ),
    ]
