# Generated by Django 4.2.4 on 2023-11-15 23:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0010_rename_category_game_categories_category_image_and_more"),
        ("games", "0011_revert_category_name"),
    ]

    operations = []
