# Generated by Django 4.2.4 on 2023-11-13 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0011_revert_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="num_winner",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="matches",
            field=models.ManyToManyField(blank=True, related_name="matches", to="games.match"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="players",
            field=models.ManyToManyField(blank=True, related_name="joined_tournaments", to=settings.AUTH_USER_MODEL),
        ),
    ]
