# Generated by Django 4.2.4 on 2023-11-16 06:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0012_merge_20231115_1702"),
        ("games", "0012_update_tournaments"),
    ]

    operations = []
