# Generated by Django 4.2.4 on 2023-11-22 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0012_update_tournaments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="match",
        ),
        migrations.AddField(
            model_name="chat",
            name="tournament",
            field=models.OneToOneField(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="games.tournament"
            ),
        ),
    ]
