# Generated by Django 4.2.4 on 2023-11-23 03:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0013_merge_20231116_0044"),
        ("games", "0013_remove_chat_match_chat_tournament"),
    ]

    operations = []
