# Generated by Django 4.2.4 on 2023-11-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0013_merge_20231116_0044"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="year_published",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
