# Generated by Django 4.2.4 on 2023-11-22 00:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0013_tournament_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="participants",
            field=models.ManyToManyField(related_name="tournaments", to=settings.AUTH_USER_MODEL),
        ),
    ]
