# Generated by Django 4.2.4 on 2023-11-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0013_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="update_on",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
