# Generated by Django 4.2.4 on 2023-11-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0013_merge_20231116_0044"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="token_id",
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name="message",
            name="update_on",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
