# Generated by Django 4.2.4 on 2023-11-22 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0014_tournament_participants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="participants",
        ),
    ]
