# Generated by Django 4.2.4 on 2023-11-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0014_remove_chat_match_chat_tournament_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="token_id",
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name="message",
            name="update_on",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(null=True),
        ),
    ]
