# Generated by Django 4.2.4 on 2023-11-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0014_alter_game_year_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="lobby",
            name="match_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
