# Generated by Django 4.2.4 on 2023-11-27 00:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0014_remove_chat_match_chat_tournament_and_more"),
        ("games", "0014_review"),
    ]

    operations = []
