# Generated by Django 4.2.4 on 2023-11-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0015_merge_20231126_1835"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
