# Generated by Django 4.2.4 on 2023-11-28 04:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0015_message_token_id_message_update_on_and_more"),
        ("games", "0016_review_is_public_alter_review_rating"),
    ]

    operations = []
