# Generated by Django 4.2.4 on 2023-12-04 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0016_update_tournaments_2"),
        ("games", "0019_alter_review_rating"),
    ]

    operations = []
