# Generated by Django 4.2.4 on 2023-12-05 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0020_merge_20231204_1517"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tournaments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="matches",
            field=models.ManyToManyField(blank=True, related_name="tournament", to="games.match"),
        ),
    ]
