# Generated by Django 4.2.4 on 2023-12-05 06:32


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0020_merge_20231204_1517"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="matches",
            field=models.ManyToManyField(blank=True, related_name="tournament", to="games.match"),
        ),
    ]
