# Generated by Django 4.2.20 on 2025-04-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0022_tournament_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="avg_rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="game",
            name="popularity",
            field=models.IntegerField(default=0),
        ),
    ]
