# Generated by Django 4.2.20 on 2025-04-27 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_base", "0001_initial"),
        ("games", "0022_tournament_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="published_guide_id",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="knowledge_base.guide"
            ),
        ),
    ]
