# Generated by Django 4.2.20 on 2025-04-21 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0022_tournament_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="game",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="games.game"
            ),
        ),
    ]
