# Generated by Django 4.2.20 on 2025-04-28 23:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0023_game_published_guide_id"),
        ("games", "0023_livechat_livechatuser_livechatmessage"),
    ]

    operations = []
