# Generated by Django 4.2.20 on 2025-04-29 02:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0023_gamelist"),
        ("games", "0023_livechat_livechatuser_livechatmessage"),
    ]

    operations = []
