# Generated by Django 4.2.20 on 2025-04-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0023_livechat_livechatuser_livechatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="avg_rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="game",
            name="popularity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="livechat",
            name="channel",
            field=models.TextField(unique=True),
        ),
    ]
