# Generated by Django 4.2.20 on 2025-04-28 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0024_game_avg_rating_game_popularity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="avg_rating",
        ),
        migrations.RemoveField(
            model_name="game",
            name="popularity",
        ),
    ]
