# Generated by Django 4.2.20 on 2025-04-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0024_merge_20250428_1822"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livechat",
            name="channel",
            field=models.TextField(unique=True),
        ),
    ]
