# Generated by Django 4.2.20 on 2025-04-30 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0024_merge_20250428_2051"),
        ("games", "0025_alter_livechat_channel"),
    ]

    operations = []
