# Generated by Django 4.2.20 on 2025-04-30 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0026_merge_20250430_1102"),
        ("games", "0026_merge_20250430_1104"),
    ]

    operations = []
