# Generated by Django 4.2.20 on 2025-05-05 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0027_merge_20250430_1134"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="users",
            field=models.ManyToManyField(blank=True, related_name="games", to=settings.AUTH_USER_MODEL),
        ),
    ]
