# Generated by Django 4.2.20 on 2025-05-01 04:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0027_merge_20250430_1134"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livechatmessage",
            name="live_chat_id",
        ),
        migrations.RemoveField(
            model_name="livechatmessage",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="livechatuser",
            name="live_chat_id",
        ),
        migrations.RemoveField(
            model_name="livechatuser",
            name="user_id",
        ),
        migrations.DeleteModel(
            name="LiveChat",
        ),
        migrations.DeleteModel(
            name="LiveChatMessage",
        ),
        migrations.DeleteModel(
            name="LiveChatUser",
        ),
    ]
