# Generated by Django 4.2.20 on 2025-05-02 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0023_feedback"),
        ("games", "0027_merge_20250430_1134"),
    ]

    operations = []
