# Generated by Django 4.2.20 on 2025-05-11 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0028_remove_livechatmessage_live_chat_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="games.game"
            ),
        ),
    ]
