# Generated by Django 4.2.20 on 2025-05-06 04:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0028_merge_0023_feedback_0027_merge_20250430_1134"),
        ("games", "0028_remove_livechatmessage_live_chat_id_and_more"),
    ]

    operations = []
