# Generated by Django 4.2.20 on 2025-05-05 23:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0028_remove_livechatmessage_live_chat_id_and_more"),
        ("games", "0028_tournament_waitlist"),
    ]

    operations = []
