# Generated by Django 4.2.20 on 2025-05-11 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0028_remove_livechatmessage_live_chat_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractiveFictionGame",
            fields=[
                (
                    "game_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="games.game",
                    ),
                ),
                ("storyline", models.TextField(blank=True, null=True)),
                ("branching_choices", models.TextField(blank=True, null=True)),
                ("playthrough_length", models.PositiveIntegerField(blank=True, null=True)),
            ],
            bases=("games.game",),
        ),
        migrations.AlterField(
            model_name="game",
            name="max_players",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="min_players",
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
