# Generated by Django 4.2.20 on 2025-05-11 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0028_remove_livechatmessage_live_chat_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractiveFictionGame",
            fields=[
                (
                    "game_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="games.game",
                    ),
                ),
                ("content_warning", models.TextField(blank=True, null=True)),
            ],
            bases=("games.game",),
        ),
    ]
