# Generated by Django 4.2.20 on 2025-05-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0028_remove_livechatmessage_live_chat_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="twine_file",
            field=models.FileField(blank=True, null=True, upload_to="twine_games/"),
        ),
    ]
