# Generated by Django 4.2.20 on 2025-05-07 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0028_game_users"),
        ("games", "0028_remove_livechatmessage_live_chat_id_and_more"),
    ]

    operations = []
