# Generated by Django 4.2.20 on 2025-05-11 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0029_game_twine_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="twine_file",
        ),
    ]
