# Generated by Django 4.2.20 on 2025-05-12 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0029_alter_review_game"),
        ("games", "0029_merge_20250507_1534"),
    ]

    operations = []
