# Generated by Django 4.2.20 on 2025-05-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0030_remove_game_twine_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="twine_file",
            field=models.FileField(blank=True, null=True, upload_to="twine_games/"),
        ),
    ]
