# Generated by Django 4.2.20 on 2025-05-12 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0031_game_twine_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="games.game"
            ),
        ),
    ]
