# Generated by Django 4.2.20 on 2025-05-12 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0029_merge_20250507_1534"),
        ("games", "0032_alter_review_game"),
    ]

    operations = []
