# Generated by Django 4.2.20 on 2025-05-12 22:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0030_merge_20250512_1728"),
        ("games", "0033_merge_0029_merge_20250507_1534_0032_alter_review_game"),
    ]

    operations = []
