# Generated by Django 4.2.20 on 2025-05-13 03:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0030_merge_0029_alter_review_game_0029_merge_20250507_1534"),
        ("games", "0034_merge_20250512_1731"),
    ]

    operations = []
