# Generated by Django 4.2.20 on 2025-05-13 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0029_interactivefictiongame"),
        ("games", "0031_alter_feedback_user_alter_review_game"),
        ("games", "0034_merge_20250512_1731"),
    ]

    operations = []
