# Generated by Django 4.2.20 on 2025-05-15 03:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0035_merge_20250512_2236"),
        ("games", "0035_merge_20250513_1435"),
    ]

    operations = []
