# Generated by Django 4.2.20 on 2025-05-13 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0035_merge_20250513_1435"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkers",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("player_1", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.player")),
                (
                    "player_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkers_player_2",
                        to="games.player",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkers_winner",
                        to="games.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckersBoard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="CheckersTurn",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("turn_number", models.PositiveIntegerField()),
                ("board", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.checkersboard")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="turns", to="games.checkers"
                    ),
                ),
                ("player", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.player")),
            ],
            options={
                "unique_together": {("game", "turn_number")},
            },
        ),
    ]
