# Generated by Django 4.2.20 on 2025-05-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0035_merge_20250513_1435"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="first_place_prize",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="prize_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="second_place_prize",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="third_place_prize",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
