# Generated by Django 4.2.20 on 2025-05-19 00:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0029_merge_20250505_1836"),
        ("games", "0035_merge_20250513_1435"),
    ]

    operations = []
