# Generated by Django 4.2.20 on 2025-05-19 04:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0036_checkers_checkersboard_checkersturn"),
        ("games", "0036_merge_20250514_2211"),
    ]

    operations = []
