# Generated by Django 4.2.20 on 2025-05-19 05:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0036_merge_20250514_2202"),
        ("games", "0037_merge_20250518_2303"),
    ]

    operations = []
