# Generated by Django 4.2.20 on 2025-05-19 04:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0036_merge_20250518_1914"),
        ("games", "0037_merge_20250518_2303"),
    ]

    operations = []
