# Generated by Django 4.2.20 on 2025-05-20 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0038_merge_20250519_0011"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkersboard",
            name="current_turn_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_turn_boards",
                to="games.player",
            ),
        ),
    ]
