# Generated by Django 4.2.20 on 2025-05-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0038_merge_20250519_0011"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkers",
            name="snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
