# Generated by Django 4.2.20 on 2025-05-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0038_merge_20250519_0011"),
    ]

    operations = [
        migrations.AddField(
            model_name="lobby",
            name="join_code",
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
