# Generated by Django 5.1.7 on 2025-05-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0038_merge_20250519_0011"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="twine_file_content",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="twine_file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
