# Generated by Django 4.2.20 on 2025-05-19 05:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0037_gamedata_delete_wordgamedata"),
        ("games", "0038_merge_20250519_0011"),
    ]

    operations = []
