# Generated by Django 4.2.20 on 2025-05-19 22:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0038_merge_20250518_2327"),
        ("games", "0038_merge_20250519_0011"),
    ]

    operations = []
