# Generated by Django 4.2.20 on 2025-05-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0039_checkers_snapshot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkers",
            name="snapshot",
        ),
        migrations.AddField(
            model_name="checkersturn",
            name="snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
