# Generated by Django 4.2.20 on 2025-05-21 02:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0039_merge_20250519_0030"),
        ("games", "0039_merge_20250520_1918"),
    ]

    operations = []
