# Generated by Django 5.1.7 on 2025-05-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0039_game_twine_file_content_game_twine_file_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="twine_file_content",
        ),
        migrations.AlterField(
            model_name="game",
            name="twine_file",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
