# Generated by Django 4.2.20 on 2025-05-21 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0029_gamequeue_alter_review_game_gamequeueentry"),
        ("games", "0039_merge_20250519_0030"),
    ]

    operations = []
