# Generated by Django 4.2.20 on 2025-05-21 21:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0040_merge_20250520_2114"),
        ("games", "0040_merge_20250521_1413"),
    ]

    operations = []
