# Generated by Django 4.2.20 on 2025-05-21 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0040_remove_game_twine_file_content_alter_game_twine_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="twine_file",
            new_name="twine_file_content",
        ),
    ]
