# Generated by Django 5.1.7 on 2025-05-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0041_merge_20250521_2013"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="content_sensitivity",
            field=models.CharField(
                choices=[("everyone", "Everyone"), ("teen", "Teen"), ("mature", "Mature")],
                default="everyone",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="genre",
            field=models.CharField(
                choices=[
                    ("fantasy", "Fantasy"),
                    ("sci-fi", "Sci-Fi"),
                    ("horror", "Horror"),
                    ("romance", "Romance"),
                    ("mystery", "Mystery"),
                    ("comedy", "Comedy"),
                    ("drama", "Drama"),
                ],
                default="not specified",
                max_length=50,
            ),
        ),
    ]
