# Generated by Django 4.2.20 on 2025-05-22 05:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0041_merge_20250521_1941"),
        ("games", "0041_merge_20250521_2013"),
    ]

    operations = []
