# Generated by Django 4.2.20 on 2025-05-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0041_merge_20250521_2013"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="game_url",
            field=models.URLField(
                blank=True, help_text="URL for embedded games (e.g., external web games)", null=True
            ),
        ),
    ]
