# Generated by Django 4.2.20 on 2025-05-23 00:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0039_merge_20250519_1723"),
        ("games", "0041_merge_20250521_2013"),
    ]

    operations = []
