# Generated by Django 4.2.20 on 2025-05-21 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0041_rename_twine_file_game_twine_file_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="twine_file_content",
            new_name="twine_file",
        ),
    ]
