# Generated by Django 4.2.20 on 2025-05-23 22:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0036_tournament_first_place_prize_and_more"),
        ("games", "0041_merge_20250521_2013"),
    ]

    operations = []
