# Generated by Django 4.2.20 on 2025-05-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0041_merge_20250521_2013"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="average_rating",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="rating",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
