# Generated by Django 4.2.20 on 2025-05-23 00:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0038_merge_20250518_2325"),
        ("games", "0041_merge_20250521_2013"),
    ]

    operations = []
