# Generated by Django 4.2.20 on 2025-05-24 01:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0040_merge_20250520_2134"),
        ("games", "0041_merge_20250521_2013"),
    ]

    operations = []
