# Generated by Django 4.2.20 on 2025-05-21 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0042_rename_twine_file_content_game_twine_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="twine_file_name",
        ),
    ]
