# Generated by Django 4.2.20 on 2025-05-25 00:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0042_merge_20250522_0043"),
        ("games", "0042_merge_20250523_1806"),
    ]

    operations = []
