# Generated by Django 4.2.20 on 2025-05-24 04:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0043_game_game_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="game_url",
        ),
    ]
