# Generated by Django 4.2.20 on 2025-05-25 03:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0042_merge_20250522_0046"),
        ("games", "0043_merge_20250524_1913"),
    ]

    operations = []
