# Generated by Django 4.2.20 on 2025-05-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0043_remove_game_twine_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="twine_file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
