# Generated by Django 4.2.20 on 2025-05-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0040_merge_20250521_1413"),
        ("games", "0044_game_twine_file_name"),
    ]

    operations = []
