# Generated by Django 4.2.20 on 2025-05-25 03:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0042_merge_20250522_0049"),
        ("games", "0044_merge_20250524_2231"),
    ]

    operations = []
