# Generated by Django 4.2.20 on 2025-05-25 03:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0042_merge_20250522_0052"),
        ("games", "0045_merge_20250524_2236"),
    ]

    operations = []
