# Generated by Django 4.2.20 on 2025-05-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0041_merge_20250521_2013"),
        ("games", "0046_auto_20250521_1607"),
    ]

    operations = []
