# Generated by Django 4.2.20 on 2025-05-25 03:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0042_merge_20250522_0053"),
        ("games", "0046_merge_20250524_2240"),
    ]

    operations = []
