# Generated by Django 4.2.20 on 2025-05-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0047_merge_20250524_2245"),
    ]

    operations = [
        migrations.AddField(
            model_name="lobby",
            name="join_code",
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
