# Generated by Django 4.2.20 on 2025-05-25 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0047_merge_20250524_2245"),
    ]

    operations = [
        migrations.AddField(
            model_name="lobby",
            name="invited_members",
            field=models.ManyToManyField(blank=True, related_name="invited_lobbies", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="lobby",
            name="join_code",
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
