# Generated by Django 4.2.20 on 2025-05-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0047_merge_20250524_2245"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="twine_file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="twine_file",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
