# Generated by Django 4.2.20 on 2025-05-25 22:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0048_game_twine_file_name_alter_game_twine_file"),
        ("games", "0048_lobby_join_code"),
    ]

    operations = []
