# Generated by Django 4.2.20 on 2025-05-26 02:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0042_game_game_url"),
        ("games", "0048_lobby_join_code"),
    ]

    operations = []
