# Generated by Django 4.2.20 on 2025-05-25 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0048_lobby_join_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_played", models.DateTimeField(auto_now_add=True)),
                ("is_completed", models.BooleanField()),
                (
                    "result",
                    models.PositiveSmallIntegerField(
                        blank=True, choices=[(0, "win"), (1, "draw"), (2, "lose"), (3, "incomplete")], null=True
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_history_entries",
                        to="games.match",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_history_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Game History",
                "unique_together": {("user", "match")},
            },
        ),
    ]
