# Generated by Django 4.2.20 on 2025-05-25 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0042_merge_20250523_1212"),
        ("games", "0048_lobby_join_code"),
    ]

    operations = []
