# Generated by Django 4.2.20 on 2025-05-26 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0042_merge_20250523_2024"),
        ("games", "0049_gamehistory"),
    ]

    operations = []
