# Generated by Django 4.2.20 on 2025-05-26 15:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0044_remove_game_game_url"),
        ("games", "0049_gamehistory"),
    ]

    operations = []
