# Generated by Django 4.2.20 on 2025-05-26 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0048_lobby_invited_members_lobby_join_code"),
        ("games", "0049_gamehistory"),
    ]

    operations = []
