# Generated by Django 5.1.7 on 2025-05-26 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0042_game_content_sensitivity_game_genre"),
        ("games", "0049_gamehistory"),
    ]

    operations = []
