# Generated by Django 4.2.20 on 2025-05-26 21:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0050_merge_0042_game_game_url_0049_gamehistory"),
        ("games", "0050_merge_20250526_1353"),
    ]

    operations = []
