# Generated by Django 4.2.20 on 2025-05-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0050_merge_20250526_0025"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="genre",
            field=models.CharField(
                choices=[
                    ("fantasy", "Fantasy"),
                    ("sci-fi", "Sci-Fi"),
                    ("horror", "Horror"),
                    ("romance", "Romance"),
                    ("mystery", "Mystery"),
                    ("comedy", "Comedy"),
                    ("drama", "Drama"),
                ],
                default="drama",
                max_length=50,
            ),
        ),
    ]
