# Generated by Django 4.2.20 on 2025-05-27 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0042_merge_20250522_1919"),
        ("games", "0051_merge_20250526_1638"),
    ]

    operations = []
