# Generated by Django 4.2.20 on 2025-05-27 03:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0051_alter_game_genre"),
        ("games", "0051_merge_20250526_1638"),
    ]

    operations = []
