# Generated by Django 4.2.20 on 2025-05-27 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0050_merge_0042_merge_20250523_2024_0049_gamehistory"),
        ("games", "0051_merge_20250526_1638"),
    ]

    operations = []
