# Generated by Django 4.2.20 on 2025-05-27 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0050_merge_0044_remove_game_game_url_0049_gamehistory"),
        ("games", "0052_merge_20250527_1350"),
    ]

    operations = []
