# Generated by Django 4.2.20 on 2025-05-27 21:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0052_merge_0051_alter_game_genre_0051_merge_20250526_1638"),
        ("games", "0052_merge_20250527_1350"),
    ]

    operations = []
