# Generated by Django 4.2.20 on 2025-05-27 21:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0052_merge_20250527_1350"),
        ("games", "0052_merge_20250527_1359"),
    ]

    operations = []
