# Generated by Django 4.2.20 on 2025-05-27 22:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0052_merge_20250527_0935"),
        ("games", "0053_merge_20250527_1615"),
    ]

    operations = []
