# Generated by Django 4.2.20 on 2025-05-27 23:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0053_merge_20250527_1648"),
        ("games", "0054_merge_20250527_1756"),
    ]

    operations = []
