# Generated by Django 4.2.20 on 2025-05-23 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("games", "0002_initial"),
        ("leaderboards", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricscore",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="metric_scores", to="users.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="metric",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="metrics", to="games.game"
            ),
        ),
        migrations.AddField(
            model_name="leaderboardprivacysetting",
            name="game",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="games.game"
            ),
        ),
        migrations.AddField(
            model_name="leaderboardprivacysetting",
            name="leaderboard",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="leaderboards.leaderboard"
            ),
        ),
        migrations.AddField(
            model_name="leaderboardprivacysetting",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.userprofile"),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="leaderboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="entries", to="leaderboards.leaderboard"
            ),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="region",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="leaderboards.region"
            ),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="leaderboard_entries", to="users.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="leaderboards", to="games.game"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leaderboardprivacysetting",
            unique_together={("user", "game", "leaderboard")},
        ),
    ]
