# Generated by Django 4.2.20 on 2025-05-21 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leaderboards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboardentry",
            name="region",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="leaderboards.region"
            ),
        ),
    ]
