# Generated by Django 4.2.20 on 2025-05-21 03:37

import chigame.users.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="display_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="friends",
        ),
        migrations.AddField(
            model_name="friendinvitation",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="group",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="bookmarked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("inbox", "Inbox"),
                    ("spam", "Spam"),
                    ("social", "Social"),
                    ("promotions", "Promotions"),
                    ("updates", "Updates"),
                    ("archived", "Archived"),
                ],
                default="inbox",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="user",
            name="moderator",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="profanity_filter",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="tokens",
            field=models.PositiveSmallIntegerField(
                default=1, validators=[django.core.validators.MaxValueValidator(3)]
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                validators=[chigame.users.models.validate_username],
                verbose_name="username",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AlterField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "FRIEND_REQUEST"),
                    (2, "REMINDER"),
                    (3, "UPCOMING_MATCH"),
                    (4, "MATCH_INVITATION"),
                    (5, "GROUP_INVITATION"),
                    (6, "ACHIEVEMENT"),
                    (7, "TOURNAMENT_INVITATION"),
                    (8, "TOURNAMENT_INVITATION_ACCEPTED"),
                    (9, "TOURNAMENT_STARTING"),
                    (10, "TOURNAMENT_ROUND_COMPLETED"),
                    (11, "TOURNAMENT_COMPLETED"),
                ]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="friendinvitation",
            unique_together={("sender", "receiver")},
        ),
        migrations.AlterUniqueTogether(
            name="notification",
            unique_together={("receiver", "actor_content_type", "actor_object_id", "type")},
        ),
        migrations.CreateModel(
            name="NotificationLabel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_labels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "user")},
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="labels",
            field=models.ManyToManyField(blank=True, related_name="notifications", to="users.notificationlabel"),
        ),
    ]
