# Generated by Django 4.2.4 on 2023-11-15 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tokens",
            field=models.PositiveSmallIntegerField(
                default=1, validators=[django.core.validators.MaxValueValidator(3)]
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "FRIEND_REQUEST"),
                    (2, "REMINDER"),
                    (3, "UPCOMING_MATCH"),
                    (4, "MATCH_PROPOSAL"),
                    (5, "GROUP_INVITATION"),
                ]
            ),
        ),
    ]
