# Generated by Django 4.2.4 on 2023-11-15 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_categories_plural"),
        ("users", "0002_user_tokens_alter_notification_type"),
    ]

    operations = []
