# Generated by Django 4.2.4 on 2023-11-03 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0003_added_notification_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="notification", to="contenttypes.contenttype"
            ),
        ),
    ]
