# Generated by Django 4.2.4 on 2023-11-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_merge_20231115_1525"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="username"),
        ),
    ]
