# Generated by Django 4.2.4 on 2023-11-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_merge_20231115_1525"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
