# Generated by Django 4.2.4 on 2023-12-05 05:31

import chigame.users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                validators=[chigame.users.models.validate_username],
                verbose_name="username",
            ),
        ),
    ]
