# Generated by Django 4.2.4 on 2023-12-05 06:32

import chigame.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0021_alter_tournament_matches"),
        ("users", "0004_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "FRIEND_REQUEST"),
                    (2, "REMINDER"),
                    (3, "UPCOMING_MATCH"),
                    (4, "MATCH_PROPOSAL"),
                    (5, "GROUP_INVITATION"),
                    (6, "MATCH_INVITATION"),
                    (7, "TOURNAMENT_INVITATION"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                validators=[chigame.users.models.validate_username],
                verbose_name="username",
            ),
        ),
        migrations.CreateModel(
            name="TournamentInvitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("accepted", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_invitations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tournament", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.tournament")),
            ],
        ),
        migrations.CreateModel(
            name="GameInvitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("accepted", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("match", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.match")),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_invitations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
