# Generated by Django 4.2.4 on 2023-11-03 02:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_added_visible_column_to_notifications"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="content_type",
            new_name="actor_content_type",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="object_id",
            new_name="actor_object_id",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="timestamp",
            new_name="first_sent",
        ),
        migrations.AddField(
            model_name="notification",
            name="last_sent",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
