# Generated by Django 4.2.20 on 2025-04-27 23:37

from django.db import migrations, models


# added is_deleted 
class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendinvitation",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
