# Generated by Django 4.2.4 on 2023-11-06 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0005_added_and_changed_names_of_cols_in_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.PositiveIntegerField(
                choices=[(1, "FRIEND_REQUEST"), (2, "REMINDER"), (3, "UPCOMING_MATCH"), (4, "MATCH_PROPOSAL")],
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="actor_content_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
        ),
    ]
