# Generated by Django 4.2.4 on 2023-12-05 22:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_notification_type_alter_user_username_and_more"),
        ("users", "0005_alter_user_username"),
    ]

    operations = []
