# Generated by Django 4.2.4 on 2023-12-05 23:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_tournamentinvitation_gameinvitation"),
        ("users", "0005_alter_user_username"),
    ]

    operations = []
