# Generated by Django 4.2.20 on 2025-04-29 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_friendinvitation_is_deleted"),
        ("users", "0006_user_moderator"),
    ]

    operations = []
