# Generated by Django 4.2.20 on 2025-05-09 04:32


from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0006_friendinvitation_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="friends",
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="bookmarked",
            field=models.BooleanField(default=False),
            name="category",
            field=models.CharField(
                choices=[
                    ("inbox", "Inbox"),
                    ("spam", "Spam"),
                    ("social", "Social"),
                    ("promotions", "Promotions"),
                    ("updates", "Updates"),
                    ("archived", "Archived"),
                ],
                default="inbox",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="user",
            name="moderator",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "FRIEND_REQUEST"),
                    (2, "REMINDER"),
                    (3, "UPCOMING_MATCH"),
                    (4, "MATCH_PROPOSAL"),
                    (5, "GROUP_INVITATION"),
                    (6, "ACHIEVEMENT"),
                ]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notification",
            unique_together={("receiver", "actor_content_type", "actor_object_id", "type")},
        ),
    ]
