# Generated by Django 4.2.20 on 2025-05-04 21:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_userprofile_friends_user_friends_and_more"),
        ("users", "0006_user_moderator"),
    ]

    operations = []
