# Generated by Django 4.2.20 on 2025-05-05 02:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_userprofile_friends_user_friends_and_more"),
        ("users", "0007_merge_20250429_0811"),
    ]

    operations = []
