# Generated by Django 4.2.20 on 2025-05-12 02:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_userprofile_friends_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendinvitation",
            unique_together=set(),
        ),
    ]
