# Generated by Django 4.2.20 on 2025-05-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_userprofile_friends_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profanity_filter",
            field=models.BooleanField(default=True),
        ),
    ]
