# Generated by Django 4.2.20 on 2025-05-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0007_merge_20250429_0811"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "FRIEND_REQUEST"),
                    (2, "REMINDER"),
                    (3, "UPCOMING_MATCH"),
                    (4, "MATCH_PROPOSAL"),
                    (5, "GROUP_INVITATION"),
                    (6, "ACHIEVEMENT"),
                ]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="friendinvitation",
            unique_together={("sender", "receiver")},
        ),
        migrations.AlterUniqueTogether(
            name="groupinvitation",
            unique_together={("friend_group", "sender", "receiver")},
        ),
        migrations.AlterUniqueTogether(
            name="notification",
            unique_together={("receiver", "actor_content_type", "actor_object_id", "type")},
        ),
    ]
