# Generated by Django 4.2.20 on 2025-05-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_notification_bookmarked_alter_notification_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
