# Generated by Django 4.2.20 on 2025-05-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0008_merge_20250504_2127"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendinvitation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "FRIEND_REQUEST"),
                    (2, "REMINDER"),
                    (3, "UPCOMING_MATCH"),
                    (4, "MATCH_PROPOSAL"),
                    (5, "GROUP_INVITATION"),
                    (6, "ACHIEVEMENT"),
                ]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notification",
            unique_together={("receiver", "actor_content_type", "actor_object_id", "type")},
        ),
    ]
