# Generated by Django 4.2.20 on 2025-05-19 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_userprofile_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="bookmarked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("inbox", "Inbox"),
                    ("spam", "Spam"),
                    ("social", "Social"),
                    ("promotions", "Promotions"),
                    ("updates", "Updates"),
                    ("archived", "Archived"),
                ],
                default="inbox",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profanity_filter",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "FRIEND_REQUEST"),
                    (2, "REMINDER"),
                    (3, "UPCOMING_MATCH"),
                    (4, "MATCH_INVITATION"),
                    (5, "GROUP_INVITATION"),
                    (6, "ACHIEVEMENT"),
                    (7, "TOURNAMENT_INVITATION"),
                    (8, "TOURNAMENT_INVITATION_ACCEPTED"),
                    (9, "TOURNAMENT_STARTING"),
                    (10, "TOURNAMENT_ROUND_COMPLETED"),
                    (11, "TOURNAMENT_COMPLETED"),
                ]
            ),
        ),
        migrations.CreateModel(
            name="NotificationLabel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_labels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "user")},
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="labels",
            field=models.ManyToManyField(blank=True, related_name="notifications", to="users.notificationlabel"),
        ),
    ]
