# Generated by Django 4.2.20 on 2025-05-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_userprofile_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="bookmarked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("inbox", "Inbox"),
                    ("spam", "Spam"),
                    ("social", "Social"),
                    ("promotions", "Promotions"),
                    ("updates", "Updates"),
                    ("archived", "Archived"),
                ],
                default="inbox",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
