# Generated by Django 4.2.20 on 2025-05-15 03:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_profanity_filter"),
        ("users", "0009_notification_bookmarked_notification_category_and_more"),
    ]

    operations = []
