# Generated by Django 4.2.20 on 2025-05-05 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_notification_type_and_more"),
        ("users", "0009_alter_friendinvitation_unique_together_and_more"),
    ]

    operations = []
