# Generated by Django 4.2.20 on 2025-05-21 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_merge_20250514_2202"),
        ("users", "0010_notificationlabel_notification_labels"),
    ]

    operations = []
