# Generated by Django 4.2.20 on 2025-05-19 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_merge_20250514_2211"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "FRIEND_REQUEST"),
                    (2, "REMINDER"),
                    (3, "UPCOMING_MATCH"),
                    (4, "MATCH_INVITATION"),
                    (5, "GROUP_INVITATION"),
                    (6, "ACHIEVEMENT"),
                ]
            ),
        ),
        migrations.CreateModel(
            name="NotificationLabel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_labels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "user")},
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="labels",
            field=models.ManyToManyField(blank=True, related_name="notifications", to="users.notificationlabel"),
        ),
    ]
