# Generated by Django 4.2.20 on 2025-05-27 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0051_merge_20250526_1638"),
        ("users", "0010_merge_20250527_0344"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendinvitation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="friendinvitation",
            name="message",
            field=models.TextField(
                blank=True, help_text="Optional personal message with the friend request", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="blocked_users",
            field=models.ManyToManyField(blank=True, related_name="blocked_by", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="user",
            name="last_seen",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorite_games",
            field=models.ManyToManyField(blank=True, related_name="favorited_by", to="games.game"),
        ),
        migrations.AlterField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "FRIEND_REQUEST"),
                    (2, "REMINDER"),
                    (3, "UPCOMING_MATCH"),
                    (4, "MATCH_INVITATION"),
                    (5, "GROUP_INVITATION"),
                    (6, "ACHIEVEMENT"),
                    (7, "TOURNAMENT_INVITATION"),
                    (8, "TOURNAMENT_INVITATION_ACCEPTED"),
                    (9, "TOURNAMENT_STARTING"),
                    (10, "TOURNAMENT_ROUND_COMPLETED"),
                    (11, "TOURNAMENT_COMPLETED"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name="RecommendationPreferences",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category_weight", models.IntegerField(default=40, help_text="Weight for game categories (0-100)")),
                ("mechanics_weight", models.IntegerField(default=30, help_text="Weight for game mechanics (0-100)")),
                (
                    "designers_weight",
                    models.IntegerField(default=15, help_text="Weight for game designers/artists (0-100)"),
                ),
                ("complexity_weight", models.IntegerField(default=10, help_text="Weight for game complexity (0-100)")),
                ("playtime_weight", models.IntegerField(default=5, help_text="Weight for game playtime (0-100)")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationLabel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_labels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "user")},
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="labels",
            field=models.ManyToManyField(blank=True, related_name="notifications", to="users.notificationlabel"),
        ),
    ]
