# Generated by Django 4.2.20 on 2025-05-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_notificationlabel_notification_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "FRIEND_REQUEST"),
                    (2, "REMINDER"),
                    (3, "UPCOMING_MATCH"),
                    (4, "MATCH_INVITATION"),
                    (5, "GROUP_INVITATION"),
                    (6, "ACHIEVEMENT"),
                    (7, "TOURNAMENT_INVITATION"),
                    (8, "TOURNAMENT_INVITATION_ACCEPTED"),
                    (9, "TOURNAMENT_STARTING"),
                    (10, "TOURNAMENT_ROUND_COMPLETED"),
                    (11, "TOURNAMENT_COMPLETED"),
                ]
            ),
        ),
    ]
