# Generated by Django 4.2.20 on 2025-05-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_notificationlabel_notification_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profanity_filter",
            field=models.BooleanField(default=True),
        ),
    ]
