# Generated by Django 4.2.20 on 2025-05-05 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_merge_20250505_1653"),
        ("users", "0010_merge_20250505_1655"),
    ]

    operations = []
