# Generated by Django 4.2.20 on 2025-05-19 04:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_group_description_alter_notification_type"),
        ("users", "0011_merge_20250518_2303"),
    ]

    operations = []
