# Generated by Django 4.2.20 on 2025-05-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0037_merge_20250518_2303"),
        ("users", "0011_merge_20250518_2303"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="favorite_games",
            field=models.ManyToManyField(blank=True, related_name="favorited_by", to="games.game"),
        ),
    ]
