# Generated by Django 4.2.20 on 2025-05-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_merge_20250518_2303"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "FRIEND_REQUEST"),
                    (2, "REMINDER"),
                    (3, "UPCOMING_MATCH"),
                    (4, "MATCH_INVITATION"),
                    (5, "GROUP_INVITATION"),
                    (6, "ACHIEVEMENT"),
                ]
            ),
        ),
    ]
