# Generated by Django 4.2.20 on 2025-05-06 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_merge_20250505_1715"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendinvitation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="groupinvitation",
            unique_together=set(),
        ),
    ]
