# Generated by Django 4.2.20 on 2025-05-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_friendinvitation_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
