# Generated by Django 4.2.20 on 2025-05-21 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_group_description_alter_group_members_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendinvitation",
            unique_together=set(),
        ),
    ]
