# Generated by Django 4.2.20 on 2025-05-19 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_user_profanity_filter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profanity_filter",
        ),
    ]
