# Generated by Django 4.2.20 on 2025-05-19 05:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_merge_20250514_2202"),
        ("users", "0012_merge_20250518_2347"),
    ]

    operations = []
