# Generated by Django 4.2.20 on 2025-05-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_friendinvitation_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("inbox", "Inbox"),
                    ("spam", "Spam"),
                    ("social", "Social"),
                    ("promotions", "Promotions"),
                    ("updates", "Updates"),
                    ("archived", "Archived"),
                ],
                default="inbox",
                max_length=20,
            ),
        ),
    ]
