# Generated by Django 4.2.20 on 2025-05-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_merge_20250519_0011"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
