# Generated by Django 4.2.20 on 2025-05-19 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_merge_20250519_0011"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationPreferences",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category_weight", models.IntegerField(default=40, help_text="Weight for game categories (0-100)")),
                ("mechanics_weight", models.IntegerField(default=30, help_text="Weight for game mechanics (0-100)")),
                (
                    "designers_weight",
                    models.IntegerField(default=15, help_text="Weight for game designers/artists (0-100)"),
                ),
                ("complexity_weight", models.IntegerField(default=10, help_text="Weight for game complexity (0-100)")),
                ("playtime_weight", models.IntegerField(default=5, help_text="Weight for game playtime (0-100)")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
