# Generated by Django 4.2.20 on 2025-05-19 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_merge_20250519_0011"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendinvitation",
            unique_together=set(),
        ),
    ]
