# Generated by Django 4.2.20 on 2025-05-24 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_friendinvitation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blocked_users",
            field=models.ManyToManyField(blank=True, related_name="blocked_by", to=settings.AUTH_USER_MODEL),
        ),
    ]
