# Generated by Django 4.2.20 on 2025-05-20 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_userprofile_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
