# Generated by Django 4.2.20 on 2025-05-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_friendinvitation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="friend_request_permission",
            field=models.CharField(
                choices=[("everyone", "Everyone"), ("friends_of_friends", "Friends of Friends"), ("nobody", "Nobody")],
                default="everyone",
                help_text="Who can send you friend requests",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("friends", "Friends Only"), ("private", "Private")],
                default="public",
                help_text="Who can view your profile",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="searchable_by_strangers",
            field=models.BooleanField(default=True, help_text="Allow strangers to find you in search"),
        ),
    ]
