# Generated by Django 4.2.20 on 2025-05-19 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_friendinvitation_unique_together"),
        ("users", "0011_group_description_alter_notification_type"),
        ("users", "0012_merge_20250518_2347"),
    ]

    operations = [] 