# Generated by Django 4.2.20 on 2025-05-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_friendinvitation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendinvitation",
            name="message",
            field=models.TextField(
                blank=True, help_text="Optional personal message with the friend request", max_length=500
            ),
        ),
    ]
