# Generated by Django 4.2.20 on 2025-05-24 00:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_friendinvitation_unique_together"),
    ]

    operations = []
