# Generated by Django 4.2.20 on 2025-05-21 04:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_userprofile_display_name_and_more"),
        ("users", "0015_alter_group_members"),
    ]

    operations = []
