# Generated by Django 4.2.20 on 2025-05-27 03:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_user_last_seen"),
        ("users", "0015_friendinvitation_message"),
    ]

    operations = []
