# Generated by Django 4.2.20 on 2025-05-27 03:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_alter_userprofile_bio"),
        ("users", "0016_merge_20250526_2228"),
    ]

    operations = []
