# Generated by Django 4.2.20 on 2025-05-27 06:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_user_blocked_users"),
        ("users", "0017_merge_20250526_2239"),
    ]

    operations = []
