# Generated by Django 4.2.20 on 2025-05-27 03:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_alter_group_members"),
        ("users", "0017_merge_20250526_2239"),
    ]

    operations = []
