# Generated by Django 4.2.20 on 2025-05-27 06:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_merge_20250523_1606"),
        ("users", "0018_merge_20250527_0128"),
    ]

    operations = []
