# Generated by Django 4.2.20 on 2025-04-27 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0022_tournament_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guide",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField()),
                ("recent_upload", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Pending"), (1, "Accepted"), (2, "Rejected"), (3, "Requested Change")], default=0
                    ),
                ),
                ("n_likes", models.IntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                ("game_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.game")),
            ],
        ),
        migrations.CreateModel(
            name="ReviewFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.TextField(blank=True, null=True)),
                ("status", models.IntegerField(choices=[(1, "Accepted"), (2, "Rejected"), (3, "Requested Change")])),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "guide_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="knowledge_base.guide"),
                ),
                (
                    "reviewer",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "guide_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="knowledge_base.guide"),
                ),
                (
                    "user_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "unique_together": {("user_id", "guide_id")},
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "guide_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="knowledge_base.guide"),
                ),
                (
                    "user_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "unique_together": {("user_id", "guide_id")},
            },
        ),
    ]
