# Generated by Django 4.2.21 on 2025-05-11 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guide",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField()),
                ("recent_upload", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Pending"), (1, "Accepted"), (2, "Rejected"), (3, "Requested Change")], default=0
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.TextField(blank=True, null=True)),
                ("status", models.IntegerField(choices=[(1, "Accepted"), (2, "Rejected"), (3, "Requested Change")])),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "guide_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="knowledge_base.guide"),
                ),
            ],
        ),
    ]
