# Generated by Django 4.2.20 on 2025-04-27 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("knowledge_base", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="like",
            name="guide_id",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="guide",
            name="n_likes",
        ),
        migrations.AddField(
            model_name="guide",
            name="favorites",
            field=models.ManyToManyField(related_name="favorite_guides", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="guide",
            name="likes",
            field=models.ManyToManyField(related_name="liked_guides", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="guide",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_guides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Favorite",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
