# Generated by Django 5.2.1 on 2025-05-20 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("games", "0002_initial"),
        ("knowledge_base", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="guide",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_guides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="guide",
            name="favorites",
            field=models.ManyToManyField(blank=True, related_name="favorite_guides", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="guide",
            name="game_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.game"),
        ),
        migrations.AddField(
            model_name="guide",
            name="likes",
            field=models.ManyToManyField(blank=True, related_name="liked_guides", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="reviewfeedback",
            name="guide_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="feedbacks", to="knowledge_base.guide"
            ),
        ),
        migrations.AddField(
            model_name="reviewfeedback",
            name="reviewer",
            field=models.ForeignKey(
                limit_choices_to={"moderator": True},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
