# Generated by Django 4.2.21 on 2025-05-11 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0002_initial"),
        ("knowledge_base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewfeedback",
            name="reviewer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="guide",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_guides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="guide",
            name="favorites",
            field=models.ManyToManyField(related_name="favorite_guides", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="guide",
            name="game_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.game"),
        ),
        migrations.AddField(
            model_name="guide",
            name="likes",
            field=models.ManyToManyField(related_name="liked_guides", to=settings.AUTH_USER_MODEL),
        ),
    ]
