# Generated by Django 4.2.20 on 2025-05-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("feedback", models.TextField(verbose_name="Feedback")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
            ],
            options={
                "verbose_name": "General Feedback",
                "verbose_name_plural": "General Feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
