# Generated by Django 4.2.20 on 2025-05-06 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("knowledge_base", "0002_alter_like_unique_together_remove_like_guide_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guide",
            name="favorites",
            field=models.ManyToManyField(blank=True, related_name="favorite_guides", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="guide",
            name="likes",
            field=models.ManyToManyField(blank=True, related_name="liked_guides", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="reviewfeedback",
            name="reviewer",
            field=models.ForeignKey(
                limit_choices_to={"moderator": True},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
