# Generated by Django 5.2.1 on 2025-05-15 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_base", "0003_alter_guide_favorites_alter_guide_likes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("feedback", models.TextField(verbose_name="Feedback")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
            ],
            options={
                "verbose_name": "General Feedback",
                "verbose_name_plural": "General Feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="reviewfeedback",
            name="guide_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="feedbacks", to="knowledge_base.guide"
            ),
        ),
    ]
