# Generated by Django 4.2.20 on 2025-05-13 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0003_alter_guide_favorites_alter_guide_likes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewfeedback",
            name="guide_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="feedbacks", to="knowledge_base.guide"
            ),
        ),
    ]
