# Generated by Django 4.2.20 on 2025-05-17 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_base", "0004_alter_reviewfeedback_guide_id"),
        ("knowledge_base", "0004_reviewfeedback_seen_alter_reviewfeedback_guide_id"),
    ]

    operations = []
