# Generated by Django 5.2.1 on 2025-05-19 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_base", "0004_generalfeedback_alter_reviewfeedback_guide_id"),
        ("knowledge_base", "0005_merge_20250517_1110"),
    ]

    operations = []
