# Generated by Django 5.2.1 on 2025-05-20 03:22

import machina.core.validators
import machina.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Update date")),
                (
                    "anonymous_key",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Anonymous user forum key"),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Subject")),
                (
                    "content",
                    machina.models.fields.MarkupTextField(
                        no_rendered_field=True,
                        validators=[machina.core.validators.MarkupMaxLengthValidator(None)],
                        verbose_name="Content",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=155, null=True, verbose_name="Username")),
                ("approved", models.BooleanField(db_index=True, default=True, verbose_name="Approved")),
                (
                    "enable_signature",
                    models.BooleanField(db_index=True, default=True, verbose_name="Attach a signature"),
                ),
                (
                    "update_reason",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Update reason"),
                ),
                (
                    "updates_count",
                    models.PositiveIntegerField(blank=True, default=0, editable=False, verbose_name="Updates count"),
                ),
                ("_content_rendered", models.TextField(blank=True, editable=False, null=True)),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["created"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=255, verbose_name="Subject")),
                ("slug", models.SlugField(max_length=255, verbose_name="Slug")),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Default topic"), (1, "Sticky"), (2, "Announce")],
                        db_index=True,
                        verbose_name="Topic type",
                    ),
                ),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[(0, "Topic unlocked"), (1, "Topic locked"), (2, "Topic moved")],
                        db_index=True,
                        verbose_name="Topic status",
                    ),
                ),
                ("approved", models.BooleanField(db_index=True, default=True, verbose_name="Approved")),
                (
                    "posts_count",
                    models.PositiveIntegerField(blank=True, default=0, editable=False, verbose_name="Posts count"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(blank=True, default=0, editable=False, verbose_name="Views count"),
                ),
                (
                    "last_post_on",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Last post added on"),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Creation date")),
                ("updated", models.DateTimeField(auto_now=True, db_index=True, verbose_name="Update date")),
            ],
            options={
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
                "ordering": ["-type", "-last_post_on"],
                "get_latest_by": "last_post_on",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rating", models.IntegerField(choices=[(1, "Like"), (-1, "Dislike")])),
            ],
        ),
    ]
