# Generated by Django 4.2.20 on 2025-05-23 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("forum", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum_conversation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="poster",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="first_post",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="forum_conversation.post",
                verbose_name="First post",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="forum",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="forum.forum",
                verbose_name="Topic forum",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="last_post",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="forum_conversation.post",
                verbose_name="Last post",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Poster",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True, related_name="topic_subscriptions", to=settings.AUTH_USER_MODEL, verbose_name="Subscribers"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Poster",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="ratings",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                related_name="ratings",
                through="forum_conversation.Vote",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="forum_conversation.topic",
                verbose_name="Topic",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Lastly updated by",
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(fields=("poster", "post"), name="unique_rating"),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(fields=["type", "last_post_on"], name="forum_conve_type_cc96d0_idx"),
        ),
    ]
