# Generated by Django 5.2.1 on 2025-05-20 22:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum_conversation", "0002_initial"),
    ]

    operations = []
