# Generated by Django 4.2.4 on 2023-11-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum_conversation", "0014_alter_post_id_alter_topic_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like_counter",
            field=models.IntegerField(blank=True, default=0, verbose_name="Likes"),
        ),
    ]
