# Generated by Django 4.2.4 on 2023-11-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum_conversation", "0016_remove_post_like_counter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rating", models.IntegerField(choices=[(1, "Like"), (-1, "Dislike")])),
            ],
        ),
    ]
