# Generated by Django 4.2.4 on 2023-11-30 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum_conversation", "0017_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="ratings",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                related_name="ratings",
                through="forum_conversation.Vote",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vote",
            name="post",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="forum_conversation.post"
            ),
        ),
        migrations.AddField(
            model_name="vote",
            name="poster",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
